{% set version = "0.0.11" %}

package:
  name: aehmc
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/aehmc/aehmc-{{ version }}.tar.gz
  sha256: cd997a39feeadd0b79de32e60626bf192dc4cc17a99d1cd25a313e19a97f310a
  patches:

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - python >=3.6
    - numpy >=1.18.1
    - scipy >=1.4.0
    - aesara >=2.1.1
    - aeppl >=0.0.5

test:
  imports:
    - aehmc.hmc
    - aehmc.nuts

about:
  home: https://github.com/aesara-devs/aehmc
  license: MIT
  summary: HMC samplers in Aesara
  license_file: LICENSE
  dev_url: https://github.com/aesara-devs/aehmc/

extra:
  recipe-maintainers:
    - maresb
    - brandonwillard
    - rlouf
    - dgerlanc
